#:schema node_modules/wrangler/config-schema.json
name = "sublink-worker-26"
main = "src/worker.jsx"
compatibility_date = "2024-07-24"
compatibility_flags = ["nodejs_compat"]

kv_namespaces = [
  { binding = "SUBLINK_KV", id = "7243f2142fb24335a5633ce63aef1192" }
]

[assets]
directory = "./public"
